clone:
  git:
    image: plugins/git
    volumes:
    - /var/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:/drone/src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
pipeline:
  validate:
    image: scireum/sirius-build
    commands:
      - mvn clean validate -U
    volumes:
      - /root/.m2:/root/.m2
      - /var/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:/drone/src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
  deploy:
    image: scireum/sirius-build
    commands:
      - sed -i 's/DEVELOPMENT-SNAPSHOT/${DRONE_TAG}/g' pom.xml
      - mvn clean deploy
    volumes:
      - /root/.m2:/root/.m2
      - /root/.gnupg:/root/.gnupg
      - /var/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:/drone/src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    when:
      event: tag
